default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  pool: 5

development:
  <<: *default
  database: springboard_development # replace with your app_name

test:
  <<: *default
  database: springboard_test # replace with your app_name
